### PR TITLE
JBIDE-19038 remove Arquillian from JBT Central's EA site - it can be found on the JBT update site so don't need it in Central/EA >> jbosstools-4.2.x

### PR DESCRIPTION
**Pull request by nickboldt**
This PR comments out Arquillian from teh EA discovery plugin, and removes the old commented out VJET stuff too. Figured while I was performing surgery on the colon I could remove the appendix, too.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Shouldn't it be moved to the non-EA catalog for JBT ?

**Comment by nickboldt** [comment]
If you mean moved from JBT Early Access to JBT Central, yes, that's the question I asked in the JIRA. https://issues.jboss.org/browse/JBIDE-19038

**Comment by mickaelistria** [comment]
+1, with a minor comment about removing some comments.

**Comment by nickboldt** [comment]
Merged.

**Pull request closed without merging**
