### PR TITLE
[JBIDE-25770] - Remove "Hybrid Mobile Project" wizard from Central

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by psrna** [comment]
Hi @jeffmaury,

I think it needs to be removed from the central-page here [1] as well.

[1] https://github.com/jbosstools/jbosstools-central-webpage/blob/e385d08a48b64f9b2d2b9e1e2307ba6d1b4f0e23/src/scripts/main.js#L11

**Comment by jeffmaury** [comment]
@psrna for me it's commented out old code. We should never keep commented out code

**Comment by psrna** [comment]
I was searching for strings and missed that is't commented out. +1 for not keeping commented out code.

**Comment by nickboldt** [comment]
See also https://github.com/jbosstools/jbosstools-central-webpage/commit/ef7e00a9bd13143ba69f766fbd9f68a59d247607 where I removed the commented code noted above.

**Pull request merged**
