### PR TITLE
Move build to jdk11.

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

### CODE REVIEW

**Comment by sbouchet** [comment]
@jeffmaury : this fix works locally to create composites sites. this cannot be verified by the pullRequest job, which  still is using jdk18. 
i propose so to 
1. switch pr job to jdk11
2. merge this and verify the master job produce the correct composite site content.

**Review by jeffmaury — APPROVED** [review]
Yes, I agree all PR jobs should be switched to Java11

**Comment by sbouchet** [comment]
testPR
(this will validate PR build using jdk11)

**Comment by sbouchet** [comment]
testPR

**Pull request merged**
